### ISSUE TITLE
VSCode: with editor.formatOnSave enabled, the extension seems to run a formatter that never completes

### ISSUE THREAD

**Issue by esthermations** [AdaCore/ada_language_server#571]
I get this message, with the progress bar scrolling along the bottom, and it never finishes or does anything until I click cancel to dismiss it.

![image](https://user-images.githubusercontent.com/10289860/97802135-709d6480-1c95-11eb-8901-4f4f5bdd9243.png)

Could the extension possibly be configured to use gnatpp for formatting? 👀

Just thought I'd point this out and see if it's solveable beyond disabling formatting altogether. 

Thank you!

**Comment by reznikmm** [comment]
@esthermations I'm unable to reproduce this, unfortunately.

1. Does "Format Document" work fine for you on the same file?
1. Could you provide a full reproducer or at least log files?
1. The extension uses `gnatpp` code base linked into executable as a library.

**Comment by reznikmm** [comment]
I can't reproduce this, so I'm closing this. Don't hesitate to provide more details to help us investigate this.

**Comment by Joebeazelman** [comment]
Where is the formatter registered in the source code?  For a while, I couldn't get the formatting to work at all. VSCode would claim there wasn't a suitable formatter and asked if I would like to download an extension for ada.

**Comment by rami3l** [comment]
I'm having the very same problem here, but just occasionally... Could you please give me some pointers on what I could do to gain more insights into this issue when it occurs next time? In the VSCode `Output` window there's just lines like `[Trace - 12:28:20 PM] Sending request 'textDocument/hover - (49)'.` with seemingly no response, so I guess there's some thing with the server but clearly this message I got isn't very helpful.

**Comment by rami3l** [comment]
cc @reznikmm 
It seems that this problem only happens when the `with` or `use` clauses are changed in the file.
If I try to change those clauses, then the formatter will run forever.

Here's a quick example that I took to reproduce this issue:
1. Clone [this project] (https://github.com/rami3l/snowpeak/tree/412cb0171de7096dc51fc66f63e5171d7732a574) and use `alr run` to initialize it.
2. Reopen VSCode.
3. Comment the first line of `snowpeak.adb like so`:
  ```ada
  -- with Ada.Text_IO; use Ada.Text_IO;

  procedure Snowpeak is
  begin
     Put_Line ("Hello, Ada!");
  end Snowpeak;
  ```
5. The formatter gets stuck.

**Comment by Joebeazelman** [comment]
I have to second it as well.  So long as the "with" statements are not modified, the Language server works fine.  If they are, it requires restarting VSCode in order to return things to normal.

**Comment by reznikmm** [comment]
This was fixed [there](https://github.com/AdaCore/gnatcoll-core/commit/0553172078189cdbc381f66a510880290f876c3e) and should work now.

**Comment by Joebeazelman** [comment]
> This was fixed [there](https://github.com/AdaCore/gnatcoll-core/commit/0553172078189cdbc381f66a510880290f876c3e) and should work now.

Is this available prebuilt, or do I have to built it myself?

**Comment by Joebeazelman** [comment]
> This was fixed [there](https://github.com/AdaCore/gnatcoll-core/commit/0553172078189cdbc381f66a510880290f876c3e) and should work now.

No. It hasn't been fixed. I'm still getting the same error, but it's improved a bit.  I lose most of the functions with the exception of syntax highlighting.  I always get an error when I save. 

```
[Trace - 8:03:28 AM] Received response 'textDocument/formatting - (119)' in 3ms. Request failed:  (-32603).
[Error - 8:03:28 AM] Request textDocument/formatting failed.
  Message: 
  Code: -32603 
[Trace - 8:03:28 AM] Sending notification 'textDocument/didSave'.
Params: {
    "textDocument": {
        "uri": "file:///Users/joebeazelman/Projects/Repos/Controller/src/Commands.ads"
    }
}


[Trace - 8:03:28 AM] Sending notification 'workspace/didChangeWatchedFiles'.
Params: {
    "changes": [
        {
            "uri": "file:///Users/joebeazelman/Projects/Repos/Controller/src/Commands.ads",
            "type": 2
        }
    ]
}

```
